spring.application.name=greening-india

server.port=8080

# DATABASE (Docker service name is correct)
spring.datasource.url=jdbc:postgresql://db:5432/greening
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - let Hibernate manage schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# IMPORTANT: disable Flyway completely (NOT USED)
spring.flyway.enabled=false

# OPTIONAL (safe for debugging)
spring.jpa.properties.hibernate.format_sql=true